/** Catálogo v2 — re-exporta módulo compacto. */
export {
  buildEnrichCatalogPrompt,
  buildCatalogSelfCritiquePrompt,
  coerceCatalogProfile,
  finalizeCatalogProfile,
  finalizeDeepCatalogProfile,
  mergeCatalogSelfCritique,
  validateProfileCoherence,
  assessProfileReadiness,
  findSiblingCatalogLabels,
  buildCatalogEmbeddingText,
  isCatalogProfileUsableForMatch,
  assertCatalogProfileComplete,
  IncompleteCatalogProfileError,
  flattenProfileForRanker,
  compactProfileForMatchJson,
  buildSceneCaptionBlock,
  extractMatchedGarmentDetails,
  type CatalogProfileV2,
  type CatalogSelfCritique,
  type CatalogEnrichmentStatus,
  type CompactGarment,
  type CompactScene,
  type FlatGarmentView,
  type FieldVisibility,
} from "./catalogProfileV2";
